config:
  target: ""
  environments:
    development:
      target: "https://***.us-east-1.amazonaws.com/dev"
      phases:
        - duration: 30
          arrivalRate: 5
          name: "###### STARTING TESTS..."